import type { NextPage } from "next";
import Head from "next/head";
// import Image from 'next/image'
import Nav from "../components/Nav";
import Hero from "../components/Hero";
import Feature from "../components/Feature";
import Testimonials from "../components/Testimonials";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Hero />
      <Feature />
      <Testimonials />
      <Footer />

      <footer></footer>
    </>
  );
};

export default Home;
